version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.dev  # Change to .env.stg or .env.prd for staging or production
    volumes:
      - .:/app  # Mount the current directory for development